### Create a new user ###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email" : "test@tewsst.fr",
    "password" : "test1w2s34"
}

### Get a new user ###
GET http://localhost:3000/auth/signup